// Autogenerated Jamon implementation
// C:/workspace_java/jamon-test/src/jamontest/JamonTestTemplate.jamon


public class JamonTestTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements JamonTestTemplate.Intf

{
  private final java.util.Date date;
  private final String[] s;
  protected static JamonTestTemplate.ImplData __jamon_setOptionalArguments(JamonTestTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public JamonTestTemplateImpl(org.jamon.TemplateManager p_templateManager, JamonTestTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    date = p_implData.getDate();
    s = p_implData.getS();
  }
  
  @Override public void renderNoFlush(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 5, 1
    jamonWriter.write("Hello, world on ");
    // 5, 17
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(date), jamonWriter);
    // 5, 27
    jamonWriter.write(".\r\nThe arguments are:\r\n");
    // 7, 1
    int l = s.length; 
    // 8, 1
    for (int i = 0; i < l; ++i )
    {
      // 8, 31
      jamonWriter.write("\r\n");
      // 9, 1
      org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(s[i]), jamonWriter);
      // 9, 11
      jamonWriter.write("\r\n");
    }
  }
  
  
}
